[functions.send-web-push]
verify_jwt = false

[functions.send-school-invitation]
verify_jwt = false

[functions.create-mercado-pago-subscription]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false

[functions.cancel-mercado-pago-subscription]
verify_jwt = false
