const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root=path.join(__dirname,'..');
const source=fs.readFileSync(path.join(root,'assisted-attendance.js'),'utf8');
const migration=fs.readFileSync(path.join(root,'supabase','migrations','105_assisted_attendance_status.sql'),'utf8');
const eventsMigration=fs.readFileSync(path.join(root,'supabase','migrations','106_siap_attendance_status_events.sql'),'utf8');

assert.match(source,/Frequência Assistida/);
assert.match(source,/normalizeName/);
assert.doesNotMatch(source,/registration|matrícula|matricula/);
assert.match(source,/thresholds\.frequentMinimum/);
assert.match(source,/thresholds\.absentMinimum/);
assert.match(source,/Usar cálculo padrão/);
assert.match(source,/Frequente:.*Faltoso:.*Necessita de Busca Ativa:/);
assert.match(source,/Necessita de Busca Ativa/);
assert.match(source,/completedMonths/);
assert.match(source,/selectedMonths/);
assert.match(source,/Aguardando as datas indicadas abaixo/);
assert.match(source,/localeCompare\(b\.name,'pt-BR'/);
assert.match(source,/if\(!state\.ready\)throw new Error/);
assert.match(source,/carometro-frequencia-leitura-0\.6\.3\.zip/);
assert.match(source,/Carregar sem compactação/);
assert.match(source,/key==='frequent'\)return ''/);
assert.match(source,/monthProgress/);
assert.match(source,/Faltam:/);
assert.match(source,/já foi capturada/);
assert.match(source,/eligibleRegisteredDays/);
assert.match(source,/matutino:12/);
assert.match(source,/vespertino:18/);
assert.match(source,/noturno:23/);
assert.match(source,/date>today\)return false/);
assert.match(source,/flatMap\(item=>eligibleRegisteredDays\(item\)\)/);
assert.doesNotMatch(source,/flatMap\(eligibleRegisteredDays\)/);
assert.match(source,/},25000\)/);
assert.match(source,/finally\{\s*control\.disabled=false/);
assert.match(source,/A leitura foi interrompida com segurança/);
assert.match(source,/data-aa-import>Importar para os cards/);
assert.match(source,/importControl\.classList\.toggle\('hidden',!state\.ready\)/);
assert.doesNotMatch(source,/if\(collectionState\(\)\.ready\) await persistCompleteCollection/);
assert.match(source,/isMobileDevice/);
assert.match(source,/max-width: 900px/);
assert.match(source,/Android\|iPhone\|iPod\|Mobile/);
assert.match(source,/if\(isMobileDevice\(\)\)return/);
assert.match(source,/turnos encerrados são considerados/);
const siapIntegration=fs.readFileSync(path.join(root,'siap-integration.js'),'utf8');
assert.match(siapIntegration,/getSiapAttendanceBadge \|\|=/);
const indexSource=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert.match(indexSource,/getSiapAttendanceBadge\?\.\(s\.id\)/);
assert.match(source,/row\.matches\.length===1/);
assert.match(source,/import_siap_attendance_results/);
assert.match(migration,/unique \(school_id, student_id, period_key\)/);
assert.match(migration,/is_active_school_member\(school_id\)/);
assert.match(migration,/can_import_siap_attendance/);
assert.match(eventsMigration,/create table if not exists public\.siap_attendance_status_events/);
assert.match(eventsMigration,/changed_at timestamptz not null default now\(\)/);
assert.match(eventsMigration,/from_status/);
assert.match(eventsMigration,/previous_status is distinct from item_status/);
assert.match(eventsMigration,/insert into public\.siap_attendance_status_events/);
assert.match(eventsMigration,/grant execute on function public\.import_siap_attendance_results/);
assert.match(eventsMigration,/insert into public\.siap_attendance_history/);
assert.match(eventsMigration,/insert into public\.siap_attendance_current/);
console.log('Frequência Assistida: identificação nominal, classificação, mês completo e persistência preparados.');
