const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const migration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '126_school_secretary_daily_attendance.sql'), 'utf8');
const configurable = fs.readFileSync(path.join(root, 'supabase', 'migrations', '127_secretary_configurable_permissions.sql'), 'utf8');
const defaultAttendance = fs.readFileSync(path.join(root, 'supabase', 'migrations', '128_secretary_default_daily_attendance.sql'), 'utf8');
const roleBoundary = fs.readFileSync(path.join(root, 'supabase', 'migrations', '133_secretary_attendance_role_boundary.sql'), 'utf8');
const invitations = fs.readFileSync(path.join(root, 'school-invitations.js'), 'utf8');
const permissions = fs.readFileSync(path.join(root, 'permissions-and-details.js'), 'utf8');
const sender = fs.readFileSync(path.join(root, 'supabase', 'functions', 'send-school-invitation', 'index.ts'), 'utf8');

assert.match(migration, /role in \('school_admin', 'coordinator', 'teacher', 'secretary'\)/);
assert.match(migration, /school_invitations_role_check[\s\S]*role in \('school_admin', 'coordinator', 'teacher', 'secretary'\)/);
assert.match(migration, /can_import_school_daily_attendance boolean not null default false/);
assert.match(migration, /enforce_secretary_restricted_permissions/);
assert.match(migration, /new\.can_view_occurrences:=false/);
assert.match(migration, /new\.can_register_occurrences:=false/);
assert.match(migration, /restrict_secretary_member_role/);
assert.match(migration, /v_invitation\.role = 'secretary'/);
assert.match(migration, /can_import_school_daily_attendance=true/);
assert.match(migration, /sm\.role in \('teacher', 'coordinator', 'secretary'\)/);
assert.match(migration, /create table public\.siap_school_daily_attendance_history/);
assert.match(migration, /create table public\.siap_school_daily_attendance_current/);
assert.match(migration, /using \(public\.is_active_school_member\(school_id\)\)/);
assert.match(migration, /item_percentage := round/);
assert.match(roleBoundary, /sm\.role='secretary'[\s\S]*coalesce\(permissions\.can_import_school_daily_attendance,false\)/);
const currentImport = roleBoundary.match(/create or replace function public\.import_siap_school_daily_attendance[\s\S]*?\$function\$;/i)?.[0] || '';
assert.doesNotMatch(currentImport, /sm\.role='school_admin'/);
assert.match(roleBoundary, /set_secretary_daily_attendance_permission/);
assert.match(roleBoundary, /actor\.role='school_admin'[\s\S]*actor\.role='coordinator'[\s\S]*can_manage_member_permissions/);
assert.match(migration, /v_target\.role<>'secretary'/);
assert.doesNotMatch(migration, /Secretaria ou Coordenação/);
assert.match(invitations, /option value="secretary">Secretário\(a\)/);
assert.match(invitations, /\['coordinator', 'secretary'\]\.includes/);
assert.match(permissions, /Liberar todas as permissões disponíveis/);
assert.match(permissions, /Secretaria nunca pode ser indicada como conselheiro de turma/);
assert.doesNotMatch(permissions, /admin\?'':schoolDailyAttendanceCheck/);
assert.match(sender, /\['coordinator', 'teacher', 'secretary'\]\.includes\(invitation\.role\)/);
assert.match(sender, /\['coordinator', 'secretary'\]\.includes\(callerMember\.role\)[\s\S]*invitation\.role !== 'teacher'/);
assert.match(configurable, /can_receive_notifications boolean not null default false/);
assert.match(configurable, /perform public\.reset_secretary_permissions\(v_member_id\)/);
assert.match(configurable, /new\.can_manage_counselors := false/);
assert.match(configurable, /sm\.role<>'secretary'/);
assert.match(configurable, /Secretaria nao pode ser conselheiro de turma/);
assert.match(configurable, /delete from public\.class_counselors/);
assert.match(configurable, /actor\.role<>'secretary' or coalesce\(ap\.can_view_occurrences,false\)/);
assert.match(configurable, /sm\.role<>'secretary' or coalesce\(p\.can_receive_notifications,false\)/);
assert.match(defaultAttendance, /can_import_school_daily_attendance=true/);
assert.match(defaultAttendance, /can_view_occurrences=false/);

console.log('Papel Secretaria: frequência inicial, permissões adicionais configuráveis e proibição de conselheiro aprovados.');
