const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const sql = fs.readFileSync(path.join(root, 'supabase/migrations/097_school_year_transition.sql'), 'utf8');
const terminalSql = fs.readFileSync(path.join(root, 'supabase/migrations/136_terminal_grade_and_flexible_year_transition.sql'), 'utf8');
const ui = fs.readFileSync(path.join(root, 'school-year-transition.js'), 'utf8');
const permissions = fs.readFileSync(path.join(root, 'permissions-and-details.js'), 'utf8');
const reports = fs.readFileSync(path.join(root, 'reports.js'), 'utf8');

assert.match(sql, /can_prepare_school_year boolean not null default false/);
assert.match(sql, /sm\.role = 'school_admin'.*sm\.role = 'coordinator'/s);
assert.match(sql, /Todos os alunos ativos precisam ter um destino/);
assert.match(sql, /insert into public\.student_class_history/);
assert.match(sql, /transition_result in \('remapped', 'repeated', 'transferred'\)/);
assert.match(sql, /student_snapshot jsonb/);
assert.match(sql, /removed_photo_paths/);
assert.match(sql, /enrollment_status = 'active'/);
assert.match(sql, /archived_at is null/);
assert.match(sql, /s\.enrollment_status = 'active' or p_student_id = s\.id/);
assert.match(sql, /update public\.classes set archived_at = now\(\)/);
assert.doesNotMatch(sql, /delete from public\.(students|classes|student_occurrences)/i);
assert.doesNotMatch(ui, /from\(['"](?:students|classes|student_occurrences)['"]\)\.delete\(\)/i);
assert.match(ui, /Como você quer preparar/);
assert.match(ui, /Sugerir próximas turmas/);
assert.match(ui, /Ajustar alunos/);
assert.match(ui, /Confirmar e preparar/);
assert.match(ui, /Preparação concluída/);
assert.match(ui, /Situação ainda não definida/);
assert.match(ui, /function renderClasses\(\)[\s\S]*updateChrome\(\);\s*\n\s*}/);
assert.match(ui, /Montar turmas do próximo ano/);
assert.match(ui, /Mover selecionados/);
assert.match(ui, /Usar turmas do ano atual/);
assert.match(ui, /data-picker-shift/);
assert.match(ui, /data-existing-class/);
assert.match(ui, /OU CRIE UMA TURMA NOVA/);
assert.match(ui, /Como distribuir/);
assert.match(ui, /Alunos de 2026/);
assert.match(ui, /data-return-student/);
assert.match(ui, /Aluno devolvido para a lista sem destino/);
assert.match(ui, /Concluiu a etapa/);
assert.match(ui, /isTerminalClass/);
assert.doesNotMatch(ui, /Deixou a escola/);
assert.match(terminalSql, /enrollment_status in \('active', 'transferred', 'concluded'\)/);
assert.match(terminalSql, /transition_result in \('remapped', 'repeated', 'transferred', 'concluded'\)/);
assert.match(terminalSql, /Aluno aprovado da 3ª série deve ser marcado como concluinte/);
assert.match(terminalSql, /Somente alunos da 3ª série podem concluir a etapa/);
assert.match(terminalSql, /next_status = 'transferred'[\s\S]*photo_path = null/);
assert.match(terminalSql, /enrollment_status = 'concluded'/);
assert.match(permissions, /set_school_year_transition_permission/);
assert.match(reports, /enrollment_status', 'transferred'/);
assert.match(reports, /\(transferido\)/);

console.log('school-year-transition: estrutura, permissão e preservação validadas');
