-- CARÔMETRO COMERCIAL
-- Transferir administração da escola.
--
-- Infraestrutura desta migration:
--   1. school_audit_log — tabela genérica de auditoria administrativa
--      ESCOLAR (não confundir com platform_audit_log, que é do painel do
--      proprietário da plataforma). Guarda o mínimo necessário, sem PII
--      duplicada (nomes/e-mails não são copiados aqui — quem lê já resolve
--      via join, exatamente como o resto do sistema faz). Vinculada à
--      escola via FK ON DELETE CASCADE: ao contrário de platform_audit_log
--      (que precisa sobreviver à exclusão da escola e por isso duplica
--      school_id/school_name em jsonb), aqui o registro só faz sentido
--      enquanto a escola existir — não há necessidade de sobreviver à
--      exclusão física, então a FK simples é suficiente e mais simples.
--      Primeiro evento: school_admin_transferred. Preparada para outros
--      eventos administrativos escolares futuros (nenhum CHECK fechado em
--      event_type, mesmo padrão de platform_audit_log).
--   2. transfer_school_admin(p_target_member_id, p_previous_admin_action) —
--      RPC transacional única. Só o school_admin ativo da escola pode
--      chamar. Promove o candidato primeiro, só depois trata o
--      administrador anterior — nunca existe um instante persistido em que
--      a escola fique sem administrador. Toda a operação é uma única
--      transação implícita da function: qualquer falha desfaz tudo.
--
-- Concorrência: a linha de schools é travada primeiro (FOR UPDATE),
-- serializando qualquer outra transferência concorrente para a mesma
-- escola (e também contra platform_archive_school/platform_restore_school,
-- que já travam essa mesma linha). As linhas de school_members do
-- candidato e do ator são travadas (FOR UPDATE) e revalidadas por completo
-- depois do lock — nunca se confia em nenhum dado lido antes de travar.
-- Repetição/duplo clique: depois de uma transferência bem-sucedida, o ator
-- deixa de ser school_admin (papel mudou ou vínculo foi removido) — uma
-- segunda chamada falha naturalmente na revalidação do papel do ator, sem
-- precisar de nenhum token de idempotência à parte.
--
-- Escolas suspensas/arquivadas: a operação exige
-- is_active_school_member(school_id) para o ator, que já embute
-- is_school_active() (status = 'active'). Uma escola arquivada OU suspensa
-- não permite a transferência por este caminho — não existe atalho aqui
-- para transferir administração de uma escola arquivada; o fluxo de
-- arquivamento/restauração da plataforma continua sendo o único caminho
-- para essas escolas.
--
-- platform_admins nunca é tocado por esta migration nem por esta RPC —
-- papel de proprietário da plataforma e papel de school_admin são
-- inteiramente independentes, como já auditado.

begin;

create table public.school_audit_log (
  id bigint generated by default as identity primary key,
  school_id uuid not null references public.schools(id) on delete cascade,
  event_type text not null,
  actor_user_id uuid references auth.users(id) on delete set null,
  previous_admin_user_id uuid references auth.users(id) on delete set null,
  new_admin_user_id uuid references auth.users(id) on delete set null,
  previous_admin_final_role text
    check (previous_admin_final_role in ('coordinator', 'teacher', 'left_school')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index school_audit_log_school_created_idx
  on public.school_audit_log (school_id, created_at desc);

alter table public.school_audit_log enable row level security;

-- Mesma hierarquia já usada em toda parte: has_school_permission() concede
-- true incondicionalmente para school_admin, e para coordenador/professor
-- só quando a flag can_view_audit (já existente na tabela de permissões,
-- até agora sem nenhuma funcionalidade real por trás dela) foi concedida
-- explicitamente pela tela de Permissões.
create policy "School members with audit access read school audit log"
on public.school_audit_log
for select
to authenticated
using (public.has_school_permission(school_id, 'can_view_audit'));

create or replace function public.transfer_school_admin(
  p_target_member_id uuid,
  p_previous_admin_action text
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_school_id uuid;
  v_school public.schools%rowtype;
  v_target public.school_members%rowtype;
  v_actor public.school_members%rowtype;
  v_previous_admin_user_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Usuário não autenticado.';
  end if;

  if p_target_member_id is null then
    raise exception 'Candidato inválido.';
  end if;

  if p_previous_admin_action not in ('coordinator', 'teacher', 'left_school') then
    raise exception 'Ação final inválida.';
  end if;

  -- school_id de um vínculo nunca muda depois de criado (não existe UPDATE
  -- em school_members.school_id em nenhum lugar do sistema) — esta leitura
  -- sem lock só serve para saber qual linha de schools travar a seguir.
  -- Nenhuma decisão de autorização é tomada com base nela: tudo é
  -- revalidado abaixo, já sob lock.
  select school_id into v_school_id
  from public.school_members
  where id = p_target_member_id;

  if v_school_id is null then
    raise exception 'Candidato não encontrado.';
  end if;

  -- Trava a escola primeiro — serializa qualquer outra transferência
  -- concorrente para a mesma escola.
  select *
    into v_school
  from public.schools
  where id = v_school_id
  for update;

  if not found then
    raise exception 'Escola não encontrada.';
  end if;

  select *
    into v_target
  from public.school_members
  where id = p_target_member_id
  for update;

  if not found or v_target.school_id <> v_school.id then
    raise exception 'Candidato não encontrado.';
  end if;

  select *
    into v_actor
  from public.school_members
  where school_id = v_school.id
    and user_id = auth.uid()
  for update;

  if not found or not public.is_active_school_member(v_school.id) then
    raise exception 'Você não possui acesso ativo a esta escola.';
  end if;

  if v_actor.role <> 'school_admin' or v_actor.status <> 'active' then
    raise exception 'Somente o administrador ativo desta escola pode transferir a administração.';
  end if;

  if v_target.user_id = v_actor.user_id then
    raise exception 'Você não pode transferir a administração para si mesmo.';
  end if;

  if v_target.status <> 'active' then
    raise exception 'O candidato selecionado não está ativo nesta escola.';
  end if;

  if v_target.role not in ('coordinator', 'teacher') then
    raise exception 'O candidato selecionado precisa ser coordenador ou professor desta escola.';
  end if;

  v_previous_admin_user_id := v_actor.user_id;

  -- 1) Promove o candidato primeiro. Enquanto isto não terminar, o ator
  -- ainda é school_admin — nunca existe um instante persistido sem
  -- administrador.
  update public.school_members
  set role = 'school_admin', updated_at = now()
  where id = v_target.id;

  -- school_admin tem acesso total pelo próprio papel, nunca pelas flags —
  -- zera tudo para não deixar nenhuma permissão antiga escondida para
  -- reaparecer se esta conta for rebaixada no futuro.
  update public.school_member_permissions
  set
    can_add_students = false, can_edit_students = false, can_delete_students = false,
    can_edit_all = false, can_edit_photo = false, can_edit_name = false,
    can_edit_class = false, can_edit_report = false,
    can_manage_observation_options = false, can_invite_teachers = false,
    can_manage_member_permissions = false, can_view_uniform = false,
    can_edit_uniform = false, can_mark_all_uniform_received = false,
    can_view_occurrences = false, can_register_occurrences = false,
    can_edit_occurrences = false, can_delete_occurrences = false,
    can_manage_counselors = false, can_view_dashboard = false,
    can_view_history = false, can_manage_alerts = false,
    can_record_followups = false, can_export_reports = false,
    can_use_bulk_actions = false, can_view_audit = false,
    can_view_class_summary = false,
    updated_at = now()
  where member_id = v_target.id;

  -- 2) Só agora trata o administrador anterior.
  if p_previous_admin_action = 'left_school' then
    -- A trigger enforce_member_permission_effective_access (em
    -- school_member_permissions) reavalia is_active_school_member() do
    -- ATOR no momento em que dispara. Se deixássemos a FK cascatear
    -- sozinha a partir do DELETE em school_members, o próprio vínculo do
    -- ator já estaria removido quando a cascata disparasse a trigger sobre
    -- a linha de permissões — e is_active_school_member() teria como
    -- avaliar exatamente essa mesma linha que está desaparecendo,
    -- retornando false e bloqueando a operação. Por isso a linha de
    -- permissões é removida primeiro, explicitamente, enquanto o vínculo
    -- do ator (e seu status='active') ainda existe — só depois o vínculo
    -- em si é removido, sem nada mais para cascatear.
    delete from public.school_member_permissions where member_id = v_actor.id;
    delete from public.school_members where id = v_actor.id;
  else
    update public.school_members
    set role = p_previous_admin_action, updated_at = now()
    where id = v_actor.id;

    -- Mesmo piso hoje usado por set_school_member_role() para as
    -- transições coordinator<->teacher — reconfirmado no código real antes
    -- de escrever esta migration.
    if p_previous_admin_action = 'coordinator' then
      update public.school_member_permissions
      set
        can_add_students = false, can_edit_students = false, can_delete_students = false,
        can_edit_all = false, can_edit_photo = false, can_edit_name = false,
        can_edit_class = false, can_edit_report = false,
        can_manage_observation_options = false, can_invite_teachers = false,
        can_manage_member_permissions = false, can_view_uniform = false,
        can_edit_uniform = false, can_mark_all_uniform_received = false,
        can_view_occurrences = false, can_register_occurrences = false,
        can_edit_occurrences = false, can_delete_occurrences = false,
        can_manage_counselors = true,
        can_view_dashboard = false, can_view_history = false,
        can_manage_alerts = false, can_record_followups = false,
        can_export_reports = false, can_use_bulk_actions = false,
        can_view_audit = false, can_view_class_summary = false,
        updated_at = now()
      where member_id = v_actor.id;
    elsif p_previous_admin_action = 'teacher' then
      update public.school_member_permissions
      set
        can_add_students = false, can_edit_students = false, can_delete_students = false,
        can_edit_all = false, can_edit_photo = false, can_edit_name = false,
        can_edit_class = false, can_edit_report = false,
        can_manage_observation_options = false, can_invite_teachers = false,
        can_manage_member_permissions = false, can_view_uniform = false,
        can_edit_uniform = false, can_mark_all_uniform_received = false,
        can_view_occurrences = true, can_register_occurrences = true,
        can_edit_occurrences = false, can_delete_occurrences = false,
        can_manage_counselors = false,
        can_view_dashboard = false, can_view_history = false,
        can_manage_alerts = false, can_record_followups = false,
        can_export_reports = false, can_use_bulk_actions = false,
        can_view_audit = false, can_view_class_summary = false,
        updated_at = now()
      where member_id = v_actor.id;
    end if;
  end if;

  insert into public.school_audit_log (
    school_id, event_type, actor_user_id,
    previous_admin_user_id, new_admin_user_id, previous_admin_final_role
  ) values (
    v_school.id, 'school_admin_transferred', auth.uid(),
    v_previous_admin_user_id, v_target.user_id, p_previous_admin_action
  );

  return jsonb_build_object(
    'school_id', v_school.id,
    'new_admin_user_id', v_target.user_id,
    'previous_admin_user_id', v_previous_admin_user_id,
    'previous_admin_final_role', p_previous_admin_action
  );
end;
$function$;

revoke all on function public.transfer_school_admin(uuid, text) from public;
revoke all on function public.transfer_school_admin(uuid, text) from anon;
grant execute on function public.transfer_school_admin(uuid, text) to authenticated;

commit;
