create table if not exists public.school_realtime_events (
  id bigint generated by default as identity primary key,
  school_id uuid not null references public.schools(id) on delete cascade,
  entity_type text not null,
  created_at timestamptz not null default now()
);

create index if not exists school_realtime_events_school_created_idx
on public.school_realtime_events (school_id, created_at desc);

alter table public.school_realtime_events enable row level security;

drop policy if exists "active_members_can_view_school_realtime_events"
on public.school_realtime_events;

create policy "active_members_can_view_school_realtime_events"
on public.school_realtime_events
for select
to authenticated
using (
  public.is_active_school_member(school_realtime_events.school_id)
);

revoke all on table public.school_realtime_events from anon;
revoke all on table public.school_realtime_events from authenticated;
grant select on table public.school_realtime_events to authenticated;

create or replace function public.emit_school_delete_realtime_event()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  -- Não cria sinais durante a exclusão em cascata da própria escola.
  if not exists (
    select 1 from public.schools s where s.id = old.school_id
  ) then
    return old;
  end if;

  delete from public.school_realtime_events
  where created_at < now() - interval '24 hours';

  insert into public.school_realtime_events (school_id, entity_type)
  values (old.school_id, tg_table_name);

  return old;
end;
$function$;

revoke all on function public.emit_school_delete_realtime_event() from public;

drop trigger if exists emit_student_delete_realtime_event on public.students;
create trigger emit_student_delete_realtime_event
after delete on public.students
for each row execute function public.emit_school_delete_realtime_event();

drop trigger if exists emit_class_delete_realtime_event on public.classes;
create trigger emit_class_delete_realtime_event
after delete on public.classes
for each row execute function public.emit_school_delete_realtime_event();

drop trigger if exists emit_observation_option_delete_realtime_event on public.observation_options;
create trigger emit_observation_option_delete_realtime_event
after delete on public.observation_options
for each row execute function public.emit_school_delete_realtime_event();

drop trigger if exists emit_class_counselor_delete_realtime_event on public.class_counselors;
create trigger emit_class_counselor_delete_realtime_event
after delete on public.class_counselors
for each row execute function public.emit_school_delete_realtime_event();

drop trigger if exists emit_occurrence_delete_realtime_event on public.student_occurrences;
create trigger emit_occurrence_delete_realtime_event
after delete on public.student_occurrences
for each row execute function public.emit_school_delete_realtime_event();

do $block$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'school_realtime_events'
  ) then
    alter publication supabase_realtime
    add table public.school_realtime_events;
  end if;
end
$block$;
